ARG PYTHON_VERSION

## build stage

FROM python:${PYTHON_VERSION}-slim AS build

ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT

# Set the working directory
WORKDIR /api

# Copy only dependencies
COPY constraints.txt ./constraints.txt

# Install all dependencies
RUN --mount=from=storage,source=constraints.txt,target=constraints-storage.txt PIP_ROOT_USER_ACTION=ignore pip install -r constraints.txt -r constraints-storage.txt \
    && python -c "import compileall; compileall.compile_path(maxlevels=1000, legacy=True)"

# Copy the rest of application code
COPY . .
COPY --from=storage . /storage
RUN rm -r langgraph_api/server.py langgraph_api/queue.py langgraph_api/cron_scheduler.py langgraph_api/lifespan.py langgraph_api/api langgraph_api/auth

# Install the application
RUN PIP_ROOT_USER_ACTION=ignore pip install --no-deps -e . /storage \
    && python -c "import compileall; compileall.compile_path(maxlevels=1000, legacy=True)" \
    && find /api/langgraph_api -type f -name '*.py' -print0 | xargs -0 rm

## final stage

FROM python:${PYTHON_VERSION}-slim AS final

ARG PYTHON_VERSION
ARG REVISION

# Copy from build stage
COPY --from=build /api /api
COPY --from=build /storage /storage
COPY --from=build /usr/local/lib/python${PYTHON_VERSION}/site-packages /usr/local/lib/python${PYTHON_VERSION}/site-packages
COPY --from=build /usr/local/bin/uvicorn /usr/local/bin/uvicorn
COPY --from=build /usr/local/bin/langgraph-verify-graphs /usr/local/bin/langgraph-verify-graphs

# Set working directory
WORKDIR /api

# Enable Python stack traces on segfaults https://stackoverflow.com/a/29246977
# Ensure Python does not buffer output, which is recommended when inside a container.
ENV PYTHONFAULTHANDLER=1 PYTHONUNBUFFERED=True PORT=8000 PIP_ROOT_USER_ACTION=ignore N_WORKERS=1 N_JOBS_PER_WORKER=10 LANGSMITH_LANGGRAPH_API_REVISION=$REVISION LANGSMITH_LANGGRAPH_API_VARIANT=trial

LABEL org.opencontainers.image.revision=$REVISION

HEALTHCHECK --interval=5s --timeout=2s --retries=5 CMD [ "python", "/api/healthcheck.py" ]

CMD exec uvicorn langgraph_api.trial:app --log-config /api/logging.json --host 0.0.0.0 --port $PORT --no-access-log
